# Generated by Django 4.2.7 on 2023-12-02 21:50

from django.db import migrations
from django.conf import settings
from django.contrib.auth.hashers import make_password


def create_superuser(apps, schema_editor):
    User = apps.get_model("chat", "CustomUser")
    admin_email = getattr(settings, 'DEFAULT_ADMIN_EMAIL', 'admin@example.com')
    admin_password = getattr(settings, 'DEFAULT_ADMIN_PASSWORD', None)
    if admin_password and not User.objects.filter(email=admin_email).exists():
        User.objects.create(
            email=admin_email,
            password=make_password(admin_password),
            is_staff=True,
            is_superuser=True,
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser, migrations.RunPython.noop),
    ]
