# Generated by Django 4.2.7 on 2025-11-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_thread_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="model",
            field=models.CharField(
                choices=[("gpt-5", "gpt-5")], default="gpt-5", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="temperature",
            field=models.FloatField(default=1),
        ),
    ]
