# Generated by Django 5.2.10 on 2026-01-21 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_thread_and_message_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., AI Engineering Fall 2026', max_length=200)),
                ('code', models.CharField(help_text='e.g., CSCI-4380-01', max_length=50, unique=True)),
                ('semester', models.CharField(help_text='e.g., Fall 2026', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive courses deny API access to enrolled students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='University student ID, used for password generation', max_length=50)),
                ('role', models.CharField(choices=[('student', 'Student'), ('ta', 'Teaching Assistant')], default='student', max_length=10)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='chat.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('role', 'student')), fields=('user',), name='unique_student_enrollment'), models.UniqueConstraint(fields=('course', 'user'), name='unique_course_user')],
            },
        ),
    ]
