# Generated by Django 5.2.10 on 2026-02-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_course_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='litellm_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='litellm_key_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
