image: cs4341/playground
registry:
  password: ${ROCKETSHIP_REGISTRY_PASSWORD}
  server: cs4341.azurecr.io
  username: cs4341
service: myapp
github:
  repo: ericmichael/llm-deployment-docker
azure:
  subscription: ${AZURE_SUBSCRIPTION_ID}
  app_service:
    app_name: csci3351
    resource_group: cs-rg-4341-scus
    additional_env:
      DATABASE_URL: ${DATABASE_URL}
      WEBSITES_CONTAINER_START_TIME_LIMIT: 500
      CUSTOM_HOSTNAME: rgvaiclass.com
      WEBSITES_ENABLE_APP_SERVICE_STORAGE: true
      WEBSITES_PORT: 8000
      ENVIRONMENT: production
      CONFIG_FILE_PATH: /usr/src/app/config/litellm-config.yaml
      LITELLM_ENABLE_VIRTUAL_KEYS: true
      LITELLM_DB_SCHEMA: litellm
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      LITELLM_PROXY_BASE_URL: http://localhost:8000/litellm
      DISABLE_ADMIN_UI: true
