"""
Django settings for aistarterkit project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import warnings
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Load environment variables from .env file
load_dotenv()

# Suppress Django's StreamingHttpResponse async iterator warning
# This is a known issue when running ASGI - the warning doesn't affect functionality
warnings.filterwarnings(
    "ignore",
    message="StreamingHttpResponse must consume synchronous iterators",
    category=Warning,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
ENV = os.getenv("ENVIRONMENT", "development")

website_hostname = os.getenv("WEBSITE_HOSTNAME")
custom_hostname = os.getenv("CUSTOM_HOSTNAME")

CSRF_TRUSTED_ORIGINS = []


def _split_hosts(raw):
    if not raw:
        return []
    return [part.strip() for part in raw.split(",") if part.strip()]


def _collect_hosts(*groups):
    hosts = []
    for group in groups:
        if not group:
            continue
        for host in group:
            host = host.strip()
            if host and host not in hosts:
                hosts.append(host)
    return hosts


trusted_hostnames = [value for value in (custom_hostname, website_hostname) if value]
for host in trusted_hostnames:
    origin = f"https://{host}"
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

default_dev_hosts = ["localhost", "127.0.0.1"]
health_check_hosts = _split_hosts(
    os.getenv("DJANGO_HEALTHCHECK_HOSTS", "169.254.130.2")
)
extra_allowed_hosts = _split_hosts(os.getenv("DJANGO_ADDITIONAL_ALLOWED_HOSTS"))

if ENV in ("development", "test"):
    DEBUG = True
    ALLOWED_HOSTS = _collect_hosts(
        default_dev_hosts,
        health_check_hosts,
        extra_allowed_hosts,
        trusted_hostnames,
    )
else:
    DEBUG = False
    ALLOWED_HOSTS = ["*"]
    ALLOWED_HOSTS.extend(
        host for host in trusted_hostnames if host not in ALLOWED_HOSTS
    )
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SAMESITE = "None"

INSTALLED_APPS = [
    "daphne",  # Must be first for ASGI support
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",  # WebSocket support
    "chat",
    "rest_framework",
    "rest_framework.authtoken",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "aistarterkit.urls"
LOGIN_REDIRECT_URL = "settings"  # Redirect to developer settings after login
LOGOUT_REDIRECT_URL = "login"  # Assuming 'login' is the name of your login URL pattern

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "aistarterkit.wsgi.application"
ASGI_APPLICATION = "aistarterkit.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Uses PostgreSQL via DATABASE_URL environment variable

DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL"),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / "assets",
]

STATIC_URL = "static/"

STATIC_ROOT = os.path.join(os.getenv("DJANGO_STATIC_ROOT", BASE_DIR), "staticfiles")

os.makedirs(STATIC_ROOT, exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "login"

OPENAI_API_TYPE = os.getenv("OPENAI_API_TYPE", "openai")
OPENAI_API_VERSION = os.getenv("OPENAI_API_VERSION", "2024-10-21")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

LITELLM_BASE_URL = os.getenv("LITELLM_BASE_URL", "http://localhost:8000/litellm")
LITELLM_SERVICE_KEY = os.getenv("LITELLM_SERVICE_KEY") or OPENAI_API_KEY or "test-litellm-service-key"
LITELLM_MASTER_KEY = os.getenv("LITELLM_MASTER_KEY")
LITELLM_DEFAULT_MODEL = os.getenv("LITELLM_DEFAULT_MODEL", "gpt-5")
LITELLM_PROXY_BASE_URL = os.getenv("LITELLM_PROXY_BASE_URL")
LITELLM_ENABLE_VIRTUAL_KEYS = os.getenv("LITELLM_ENABLE_VIRTUAL_KEYS", "false").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
_litellm_model_env = os.getenv("LITELLM_MODEL_LIST")
if _litellm_model_env:
    _litellm_models = [value.strip() for value in _litellm_model_env.split(",") if value.strip()]
else:
    _litellm_models = []
if LITELLM_DEFAULT_MODEL not in _litellm_models:
    _litellm_models.append(LITELLM_DEFAULT_MODEL)
LITELLM_MODEL_LIST = _litellm_models or [LITELLM_DEFAULT_MODEL]

# Azure OpenAI Settings
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
# The Azure Inference (Responses/Assistants/Vector Stores) API version.
# Default to the current preview that defines the /responses endpoint.
AZURE_OPENAI_INFERENCE_API_VERSION = os.getenv(
    "AZURE_OPENAI_INFERENCE_API_VERSION", "2025-04-01-preview"
)

# Passthrough debugging (adds verbose server logs and optional debug headers)
DEBUG_OPENAI_PASSTHROUGH = os.getenv("DEBUG_OPENAI_PASSTHROUGH", "false").lower() in (
    "1",
    "true",
    "yes",
    "on",
)

AUTH_USER_MODEL = "chat.CustomUser"

DEFAULT_ADMIN_USERNAME = os.getenv("DEFAULT_ADMIN_USERNAME")

DEFAULT_ADMIN_EMAIL = os.getenv("DEFAULT_ADMIN_EMAIL")

DEFAULT_ADMIN_PASSWORD = os.getenv("DEFAULT_ADMIN_PASSWORD")

# ------------------------------------------------------------
# Logging configuration for passthrough debugging
# ------------------------------------------------------------
# This routes DEBUG logs from chat.views to the console so that
# DEBUG_OPENAI_PASSTHROUGH (or ?debug=1) messages are visible.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "[%(levelname)s] %(asctime)s %(name)s: %(message)s",
            "datefmt": "%H:%M:%S",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        }
    },
    "loggers": {
        # Our passthrough endpoint logs here
        "chat.views": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        # Keep request libraries quieter unless there are warnings/errors
        "requests": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "urllib3": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}
